---
- name: Get version information from Cisco switch
  hosts: ASR_920
  gather_facts: 'no'
  connection: network_cli
  vars_files:
   - group_vars/vault.yml


  vars:
    #    ansible_network_os: cisco.ios.ios
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"
    ansible_network_os: ios
    ansible_connection: network_cli


  tasks:
    - name: Run show version
      cisco.ios.ios_command:
        commands:
          - show version
      register: version_output

    - name: Display the output
      debug:
        var: version_output.stdout_lines
